version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=flask_backend/app.py
      - ETL_CLIENT_ID=${ETL_CLIENT_ID}
      - ETL_CLIENT_SECRET=${ETL_CLIENT_SECRET}
    command: flask run --host=0.0.0.0