FROM apache/airflow:latest

USER root
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk python3 python3-pip && \ 
    apt-get clean

# Set JAVA_HOME environment variable
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64
COPY entrypoint-airflow.sh .
RUN chmod +x entrypoint-airflow.sh

# RUN chown -R airflow:root /opt/spark/
USER airflow

COPY requirements_airflow.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

USER root
ENTRYPOINT ["./entrypoint-airflow.sh"]